name: Test and Deploy Frontend
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install --allow-scripts

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test --parallel tests/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install --allow-scripts

      - name: Build dist folder
        run: deno task build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=vite-flask-demo
